### ISSUE TITLE
Test upcoming update

### ISSUE THREAD

**Issue by Tectato** [Tectato/BetterCommandBlockUI#30]
Spent some time over the last few weeks overhauling major parts of the code to address some of the accumulated issues, namely #13, #18, some of #22, and #28.

To summarize, this update adds/changes the following:
- Added a proper config screen with ModMenu support
- Moved all previous configuration stuff from the tools window to the config screen, added button for config screen to tools window instead
- Added option to specify whether line breaks are added before and/or after parentheses and commas
- Added ability to select text by clicking & dragging
- Added better per-word erasing and cursor movement (i.e. when holding CTRL)
- Limited scroll bar resizing to a fixed minimum (No more miniscule scrollbar on very long commands)

Before I release this on the usual platforms I'd appreciate it if some of you could check this out in its current state, to find any glaring issues I missed (I've had a report of line breaks potentially not working at all but can't replicate it locally) and to confirm that the requested features have been implemented to your satisfaction.

**Comment by Tectato** [comment]
Here's the current build: [bettercommandblockui-dev.zip](https://github.com/Tectato/BetterCommandBlockUI/files/14158735/bettercommandblockui-dev.zip)

**Comment by Tectato** [comment]
The above build is for 1.20.3 and 1.20.4, if there are no major issues i'll attempt to backport it to 1.20 and 1.19

**Comment by Tectato** [comment]
I've put out an alpha release of this on the Modrinth page for 1.20.3/1.20.4, further changes include replacing the "copy to clipboard" button of the pi fraction selector with a text box which shows the current value, and adding a color selector with integer and hex outputs

**Comment by JasonHorkles** [comment]
The following checked items don't seem to save nor even apply in the preview:
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51760372/4a328f85-4d89-4cee-b52b-3918001e611b)

**Comment by Tectato** [comment]
Damn thats what I was worried about. So there are just no line breaks anywhere? Which MC version and modloader are you using? Are there any errors in the log?

**Comment by JasonHorkles** [comment]
There were line breaks everywhere, the options just weren't changing it. However, after restarting the game, it seems to work now? Maybe it didn't like an old config file or something.

Using Fabric 0.15.3 with 1.20.4

The following error is thrown out:
```
[12:49:31] [Render thread/INFO]: [STDOUT]: [MLCS::refreshRenderPos] Error:
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.ui.MultiLineCommandSuggestor.refreshRenderPos(MultiLineCommandSuggestor.java:68)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.ui.MultiLineTextFieldWidget.refreshSuggestorPos(MultiLineTextFieldWidget.java:980)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.ui.MultiLineTextFieldWidget.onChanged(MultiLineTextFieldWidget.java:551)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.ui.MultiLineTextFieldWidget.method_1883(MultiLineTextFieldWidget.java:945)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_342.method_1872(class_342.java:275)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.ui.MultiLineTextFieldWidget.method_1852(MultiLineTextFieldWidget.java:526)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.ui.MultiLineTextFieldWidget.setRawText(MultiLineTextFieldWidget.java:532)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.ui.MultiLineTextFieldWidget.refreshFormatting(MultiLineTextFieldWidget.java:537)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.config.ConfigScreen.checkboxCallback(ConfigScreen.java:235)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.config.ConfigScreen$1.onValueChange(ConfigScreen.java:82)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_4286.method_25306(class_4286.java:112)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_4264.method_25348(class_4264.java:48)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_339.method_25402(class_339.java:145)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_4069.method_25402(class_4069.java:38)
[12:49:31] [Render thread/INFO]: [STDOUT]: bettercommandblockui.main.config.ConfigScreen.method_25402(ConfigScreen.java:245)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_312.method_1611(class_312.java:99)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_437.method_25412(class_437.java:414)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_312.method_1601(class_312.java:99)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_312.method_22686(class_312.java:180)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_1255.execute(class_1255.java:102)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_312.method_22684(class_312.java:180)
[12:49:31] [Render thread/INFO]: [STDOUT]: org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[12:49:31] [Render thread/INFO]: [STDOUT]: org.lwjgl.system.JNI.invokeV(Native Method)
[12:49:31] [Render thread/INFO]: [STDOUT]: org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509)
[12:49:31] [Render thread/INFO]: [STDOUT]: com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_310.method_1523(class_310.java:1352)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.class_310.method_1514(class_310.java:888)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.minecraft.client.main.Main.main(Main.java:265)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[12:49:31] [Render thread/INFO]: [STDOUT]: net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[12:49:31] [Render thread/INFO]: [STDOUT]: org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[12:49:31] [Render thread/INFO]: [STDOUT]: org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
[12:49:31] [Render thread/INFO]: [STDOUT]: org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
I didn't check if that happens constantly or when changing the option though

**Comment by Tectato** [comment]
I think an old config file was likely the cause, I'll see if I can fix that. That error there shouldn't cause that bug, though that's also something I should fix. Thanks for the info!

**Comment by Tectato** [comment]
Alright I could confirm that the issue was caused by an old config file, I've put out an update on Modrinth that should fix that and the error message

**Comment by JasonHorkles** [comment]
Seems to be working well so far!

**Comment by Tectato** [comment]
That's good to hear

**Comment by YoshiRulz** [comment]
On alpha 3, config is sometimes wiped on launch. I'm not sure, but I think it might be that if the read file has anything non-default, then the defaults are written to disk, but what was read remains in memory so it appears normal. There's nothing in the log. The only other mods installed are Fabric API 0.96.1 and Mod Menu 9.0.0.

**Comment by JasonHorkles** [comment]
I second that, my config seems to be getting reset. I don't think saving on game close is the proper way to save the config, but rather when the settings menu is closed.

**Comment by JasonHorkles** [comment]
Found another issue, pressing ctrl + backspace in the UI when the cursor is at the start will crash the game.

```
Description: keyPressed event handler

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:1519)
	at bettercommandblockui.main.ui.MultiLineTextFieldWidget.getWordLength(MultiLineTextFieldWidget.java:344)
	at bettercommandblockui.main.ui.MultiLineTextFieldWidget.method_1877(MultiLineTextFieldWidget.java:374)
	at bettercommandblockui.main.ui.MultiLineTextFieldWidget.erase(MultiLineTextFieldWidget.java:329)
	at bettercommandblockui.main.ui.MultiLineTextFieldWidget.method_25404(MultiLineTextFieldWidget.java:466)
	at net.minecraft.class_4069.method_25404(class_4069.java:76)
	at net.minecraft.class_437.method_25404(class_437.java:131)
	at bettercommandblockui.main.ui.screen.AbstractBetterCommandBlockScreen.method_25404(AbstractBetterCommandBlockScreen.java:242)
	at net.minecraft.class_309.method_1454(class_309.java:407)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_309.method_1466(class_309.java:403)
	at net.minecraft.class_309.method_22678(class_309.java:492)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:492)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by Tectato** [comment]
Yeah saving on exiting the config screen does make more sense, I think when I made it save on exit I hadn't even implemented the config screen yet.
And great catch on the crash! That's exactly the sort of thing I usually miss when testing on my own.
I've put out another version on modrinth to address both of those issues

**Comment by JasonHorkles** [comment]
I can't remember, wasn't there an option to change the default command block output state in the older version? I could just be thinking of something else though
![image](https://github.com/Tectato/BetterCommandBlockUI/assets/51760372/c6c88fcf-2ae4-41de-8ccd-d839443403f6)

**Comment by Tectato** [comment]
There wasn't but that's a good idea actually, I'll add an option for it

**Comment by Tectato** [comment]
I put out a new alpha with checkboxes for the default output state and whether output should be shown by default. Also includes per-word text wraparound.
Idk if the way the output state checkbox works right now is very intuitive, I'd appreciate feedback and ideas on that. Right now there's no way to tell whether the previous state of a commandblock was overwritten by the default when you open the UI, though i also don't know if that really matters

**Comment by JasonHorkles** [comment]
Seems to be pretty solid, although I don't really see why the checkbox for the output should be disabled when output isn't active first. Other than that it's pretty good though! I appreciate all the work you've done!!

**Comment by Tectato** [comment]
I figured it only being toggleable when the output is shown would make it clearer that it relates to that view. I also wanted to emphasize that it acts differently to the other checkbox, which when checked makes the currently selected state the default.

**Comment by Tectato** [comment]
Release is out for 1.19.4+,
If you come across any bugs in those, please open a new issue
