### ISSUE TITLE
[1.21.3] Instant game crash upon opening UI

### ISSUE THREAD

**Issue by FlailoftheLord** [Tectato/BetterCommandBlockUI#58]
Game crashes  instantly upon  interacting with a command block to open the UI.
Mod Version: 0.5.2a
Fabric Loader: 0.16.9
FabricAPI version: 0.107.0+1.21.3
Game Version: 1.21.3
Mods installed: FabricAPI + BetterCommandBlockUI (versions listed above)

Stacktrace:
```err

Time: 2024-11-04 17:28:32
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/class_2753
	at knot//net.minecraft.class_2288.redirect$zzc000$bettercommandblockui$openBetterCommandBlockScreen(class_2288.java:524)
	at knot//net.minecraft.class_2288.method_55766(class_2288.java:142)
	at knot//net.minecraft.class_4970$class_4971.method_55781(class_4970.java:1217)
	at knot//net.minecraft.class_636.method_41934(class_636.java:347)
	at knot//net.minecraft.class_636.method_41933(class_636.java:319)
	at knot//net.minecraft.class_636.method_41931(class_636.java:280)
	at knot//net.minecraft.class_636.method_2896(class_636.java:318)
	at knot//net.minecraft.class_310.method_1583(class_310.java:1776)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2048)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1870)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1313)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2753
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_2288.redirect$zzc000$bettercommandblockui$openBetterCommandBlockScreen(class_2288.java:524)
	at knot//net.minecraft.class_2288.method_55766(class_2288.java:142)
	at knot//net.minecraft.class_4970$class_4971.method_55781(class_4970.java:1217)
	at knot//net.minecraft.class_636.method_41934(class_636.java:347)
	at knot//net.minecraft.class_636.method_41933(class_636.java:319)
	at knot//net.minecraft.class_636.method_41931(class_636.java:280)
	at knot//net.minecraft.class_636.method_2896(class_636.java:318)
	at knot//net.minecraft.class_310.method_1583(class_310.java:1776)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2048)

-- Uptime --
Details:
	JVM uptime: 16.364s
	Wall uptime: 11.863s
	High-res time: 11.492s
	Client ticks: 148 ticks / 7.400s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:957)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['FlailoftheLord'/109, l='ClientLevel', x=-12.50, y=73.00, z=171.50]]
	Chunk stats: 5041, 452
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,75,176), Section: (at 0,11,0 in -1,4,11; chunk contains blocks -16,-64,176 to -1,319,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 302 game time, 302 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 147
```

LMK if you need more information such as graphics & rendering information.

**Comment by Tectato** [comment]
Hm, I can't seem to replicate this crash. Are you sure you have the 1.21.3 release of 0.5.2a?

**Comment by FlailoftheLord** [comment]
It could likely be an issue with the Menu rendering on my specific system...
https://www.youtube.com/watch?v=2kPxXtXgKFU
game quits out and crashes the entire window the moment i click on the command block.

**Comment by FlailoftheLord** [comment]
For people using MultiMC or a similar fork, the app will cache mods if they have the same name... so even though it said the mod was updated, it just kept the old mod file  for 1.21.1 
Deleting the mod and re-downloading solved my issue.
